In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [70]:
dataset = pd.read_csv('CKD.csv')

In [71]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [72]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [73]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [74]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [75]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [76]:
independent= dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [77]:
dependent=dataset [['classification_yes']]

In [78]:
independent.shape

(399, 27)

In [79]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [80]:
dependent.shape

(399, 1)

In [81]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [82]:
X = independent
y = dependent

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [83]:
from sklearn.model_selection import GridSearchCV


param_grid = {
    'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]  
}
         
grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X, y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]},
             scoring='f1_weighted', verbose=3)

In [65]:
from sklearn.naive_bayes import ComplementNB

In [84]:
from sklearn.model_selection import GridSearchCV


param_grid = {
    'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],  
      
}
         
grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X, y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]},
             scoring='f1_weighted', verbose=3)

In [34]:
from sklearn.naive_bayes import CategoricalNB

In [86]:
from sklearn.model_selection import GridSearchCV


{'alpha': [0.1, 0.5, 1.0, 1.5, 2.0], 
    'fit_prior': [True, False]  
}
         
grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X, y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]},
             scoring='f1_weighted', verbose=3)

In [87]:
re=grid.cv_results_
grid_predictions = grid.predict(X) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y, grid_predictions)

In [88]:
from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'alpha': 0.1}: 0.9974953761738116

In [89]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[150   0]
 [  1 248]]

In [90]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399

In [91]:
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(dependent, grid.predict_proba(independent)[:,1])
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 1.0

In [92]:
table=pd.DataFrame.from_dict(re)

In [93]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.098590,0.012531,0.053856,0.022013,0.1,{'alpha': 0.1},0.962618,NaN,NaN,NaN,NaN,NaN,NaN,1
1,0.063369,0.005780,0.017384,0.013391,0.5,{'alpha': 0.5},0.962618,NaN,NaN,NaN,NaN,NaN,NaN,1
2,0.058314,0.005875,0.032866,0.009134,1.0,{'alpha': 1.0},0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
3,0.056198,0.008003,0.014134,0.007743,1.5,{'alpha': 1.5},0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
4,0.046877,0.000004,0.018750,0.006250,2.0,{'alpha': 2.0},0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1

In [94]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("Sg B 0 OR 1:"))
sg_c_input=float(input("Sg C 0 OR 1:"))
sg_d_input=float(input("Sg D 0 OR 1:"))
sg_e_input=float(input("Sg E 0 OR 1:"))
rbc_normal_input=float(input("Rbc Normal 0 or 1:"))
pc_normal_input=float(input("Pc Normal 0 or 1:"))
pcc_present_input=float(input("Pcc Present 0 or 1:"))
ba_present_input=float(input("Ba Present 0 or 1:"))
htn_yes_input=float(input("Htn Yes 0 or 1:"))
dm_yes_input=float(input("Dm Yes 0 or 1:"))
cad_yes_input=float(input("Cad Yes 0 or 1:"))
appet_yes_input=float(input("Appet Yes 0 or 1:"))
pe_yes_input=float(input("Pe Yes 0 or 1:"))
ane_yes_input=float(input("Ane Yes 0 or 1:"))

Age: 34
BP: 44
AL: 4
SU: 2
BGR: 100
BU: 150
SC: 40
SOD: 140
POT: 30
HRMO: 10
PCV: 40
WC: 2000
RC: 5
Sg B 0 OR 1: 1
Sg C 0 OR 1: 0
Sg D 0 OR 1: 1
Sg E 0 OR 1: 0
Rbc Normal 0 or 1: 1
Pc Normal 0 or 1: 0
Pcc Present 0 or 1: 1
Ba Present 0 or 1: 0
Htn Yes 0 or 1: 1
Dm Yes 0 or 1: 0
Cad Yes 0 or 1: 1
Appet Yes 0 or 1: 0
Pe Yes 0 or 1: 1
Ane Yes 0 or 1: 0

In [95]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

In [96]:
import pickle
filename="finalized_model_Naive Bayes_GridSearchCV.sav"
pickle.dump(grid,open(filename, 'wb'))

In [97]:
loaded_model=pickle.load(open("finalized_model_Naive Bayes_GridSearchCV.sav", 'rb'))
result=loaded_model.predict
result

<bound method BaseSearchCV.predict of GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]},
             scoring='f1_weighted', verbose=3)>

In [98]:
import numpy as np
def inverse_transform_dummies_with_if(array):
      result = np.array([0])

if np.array_equal(result, np.array([0])):
    print("No")
else:
    print("Yes")

Yes